name: CI Pipeline Render Server

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Node 22 setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Check node & npm versions
        run: |
          echo node:; node -v
          echo npm:; npm -v

      - name: npm install client dependencies
        run: npm install -w client

      - name: Type Check
        run: npx tsc -p client/tsconfig.json --noEmit

      - name: Build
        run: npm run build:render -w client

      # run linter
      # run unit-test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'shopping-artifact'
          path: client/dist/

