name: CI/CD Pipeline - Build & Deploy GitHub Pages with Render Server

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Node 22 setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Check node & npm versions
        run: |
          echo node:; node -v
          echo npm:; npm -v

      - name: npm install client dependencies
        run: npm install -w client

      - name: Type Check
        run: npx tsc -p client/tsconfig.json --noEmit

      - name: Build For Render Server
        run: npm run build:render -w client
        env:
          VITE_BASE_PATH: /shopping/

      # run linter
      # run unit-test

      - name: Upload Build Artifact for Manual Download
        uses: actions/upload-artifact@v4
        with:
          name: 'shopping-artifact-render-server'
          path: client/dist/

      - name: Upload Build Artifact for Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist/

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
